# Generated by Django 5.2 on 2025-04-27 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(choices=[('Python Basics', 'Python Basics'), ('Advanced Python', 'Advanced Python'), ('Python', 'Python'), ('Regular Expressions', 'Regular Expressions'), ('Database/SQL', 'Database/SQL'), ('Django', 'Django'), ('REST', 'REST'), ('Data Libraries', 'Data Libraries'), ('Mathematics', 'Mathematics'), ('Machine Learning', 'Machine Learning'), ('Deep Learning', 'Deep Learning'), ('Gen AI', 'Gen AI'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('Bootstrap', 'Bootstrap'), ('Java script', 'Java script'), ('React JS', 'React JS')], max_length=40, unique=True)),
                ('duration', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(80)], verbose_name='Duration (days)')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
