# Generated by Django 5.1.7 on 2025-04-28 04:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('tentative', models.BooleanField(default=False)),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('days', models.CharField(blank=True, max_length=255, verbose_name='Days')),
                ('status', models.CharField(choices=[('created', 'Created'), ('open', 'Registrations Open'), ('freezed', 'Freezed'), ('completed', 'Completed')], default='created', max_length=20)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(200)], verbose_name='Duration (days)')),
                ('fees', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(5000), django.core.validators.MaxValueValidator(80000)], verbose_name='Course Fee (Rs.)')),
                ('dummy_registrations', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)], verbose_name='Dummy Registrations')),
                ('language', models.CharField(choices=[('', ''), ('Telugu', 'Telugu'), ('English', 'English')], default='', max_length=15, verbose_name='Language')),
                ('youtube_link', models.URLField(blank=True, null=True, verbose_name='Demo Link')),
                ('class_room_link', models.URLField(blank=True, null=True, verbose_name='Online Classroom Link')),
                ('course_material_link', models.URLField(blank=True, null=True, verbose_name='Material Link')),
                ('quiz_link', models.URLField(blank=True, null=True, verbose_name='Weekly Test Link')),
                ('poc_name', models.CharField(blank=True, max_length=50, verbose_name='Admin Name')),
                ('poc_mobile_no', models.CharField(blank=True, help_text='This is Batch Admin Mobile number and will be shared to entire batch students.', max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Mobile number must be exactly 10 digits.')], verbose_name='Admin Mobile Number')),
            ],
        ),
    ]
