# Generated by Django 5.1.7 on 2025-04-28 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batchapp', '0001_initial'),
        ('courseapp', '0001_initial'),
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseapp.course'),
        ),
        migrations.AddField(
            model_name='batch',
            name='trainers',
            field=models.ManyToManyField(to='trainers.trainer', verbose_name='Trainers'),
        ),
    ]
