# Generated by Django 5.1.7 on 2025-04-28 04:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topicapp', '0001_initial'),
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, unique=True)),
                ('description', models.TextField(max_length=1000)),
                ('duration', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(200)], verbose_name='Duration (days)')),
                ('fees', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5000), django.core.validators.MaxValueValidator(80000)], verbose_name='Course Fee (Rs.)')),
                ('uploaded_file', models.FileField(upload_to='documents/', verbose_name='Course Content')),
                ('image', models.CharField(choices=[], max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('topic', models.ManyToManyField(to='topicapp.topic')),
                ('trainers', models.ManyToManyField(to='trainers.trainer', verbose_name='Trainers')),
            ],
        ),
    ]
