# Generated by Django 5.1.7 on 2025-04-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.CharField(choices=[('images/complete-python.jpg', 'complete-python.jpg'), ('images/data-science.jpg', 'data-science.jpg'), ('images/frontend-technology.jpg', 'frontend-technology.jpg'), ('images/python-fullstack.jpg', 'python-fullstack.jpg')], max_length=255),
        ),
    ]
