# Generated by Django 5.1.7 on 2025-04-28 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_coursefeedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursefeedback',
            old_name='user',
            new_name='trainer',
        ),
    ]
