# Generated by Django 5.1.7 on 2025-04-28 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
        ('userapp', '0003_rename_user_coursefeedback_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefeedback',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainers.trainer'),
        ),
    ]
