# Generated by Django 5.1.7 on 2025-04-28 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_remove_story_type_remove_story_user_story_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefeedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
