# Generated by Django 5.1.7 on 2025-04-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_coursefeedback_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefeedback',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Created', max_length=20),
        ),
    ]
